interface ScheduleEvent {
  id: number
  title: string
  speaker: string
  type: "X Space" | "Workshop" | "Tour" | "Party"
  stage: "MainStage"
  startTime: string
  endTime: string
  timeSlotStart: number
  timeSlotEnd: number
  duration: number
  startTimePST: string
  endTimePST: string
}

interface StageSchedule {
  [stageName: string]: ScheduleEvent[]
}

interface DaySchedule {
  [key: string]: StageSchedule
}

// Helper function to convert UTC time to PST (UTC - 7 hours)
const convertToPST = (utcTime: string): string => {
  if (utcTime === "Midday") return "05:00"
  if (utcTime === "Midnight") return "17:00"

  const hour = parseInt(utcTime.split(":")[0])
  let pstHour = hour - 7

  // Handle day boundary crossing
  if (pstHour < 0) {
    pstHour += 24
  }

  // Format with leading zero if needed
  const formattedHour = pstHour.toString().padStart(2, "0")
  return `${formattedHour}:00`
}

const timeSlots: string[] = [
  "10:00",
  "11:00",
  "Midday",
  "13:00",
  "14:00",
  "15:00",
  "16:00",
  "17:00",
  "18:00",
  "19:00",
  "20:00",
  "21:00",
  "22:00",
  "23:00",
  "Midnight",
  "01:00",
  "02:00",
]

const stages = ["MainStage"] as const

const scheduleData: DaySchedule = {
  "sept-24": {
    MainStage: [
      {
        id: 1,
        title: "The 101 on Decentraland Art Week: Launch Your Own Gallery!",
        speaker: "Bay Backner & Guests",
        type: "X Space",
        stage: "MainStage",
        startTime: "11:00",
        endTime: "12:00",
        timeSlotStart: 1,
        timeSlotEnd: 1,
        duration: 1,
        startTimePST: "04:00",
        endTimePST: "05:00",
      },
      {
        id: 2,
        title:
          "Behind the Build: How 7 Artists Turned Ideas into Immersive Art",
        speaker: "Dana Mart",
        type: "Workshop",
        stage: "MainStage",
        startTime: "12:00",
        endTime: "13:00",
        timeSlotStart: 2,
        timeSlotEnd: 2,
        duration: 1,
        startTimePST: "05:00",
        endTimePST: "06:00",
      },
      {
        id: 3,
        title: "LIVE TOUR 1",
        speaker: "Art Week Artists",
        type: "Tour",
        stage: "MainStage",
        startTime: "13:00",
        endTime: "14:00",
        timeSlotStart: 3,
        timeSlotEnd: 3,
        duration: 1,
        startTimePST: "06:00",
        endTimePST: "07:00",
      },
      {
        id: 4,
        title:
          "Your First Virtual Gallery: A Step-by-Step Build in Decentraland",
        speaker: "Nico Earnshaw",
        type: "Workshop",
        stage: "MainStage",
        startTime: "14:00",
        endTime: "15:00",
        timeSlotStart: 4,
        timeSlotEnd: 4,
        duration: 1,
        startTimePST: "07:00",
        endTimePST: "08:00",
      },
      {
        id: 5,
        title:
          "Find Your Next Collab! Easy, Fun Networking Led by a Virtual Host",
        speaker: "Bay Backner",
        type: "Workshop",
        stage: "MainStage",
        startTime: "15:00",
        endTime: "16:00",
        timeSlotStart: 5,
        timeSlotEnd: 5,
        duration: 1,
        startTimePST: "08:00",
        endTimePST: "09:00",
      },
      {
        id: 6,
        title: "Your Art in Decentraland? Here's How to Make It Happen",
        speaker: "Kim Currier & Guests",
        type: "X Space",
        stage: "MainStage",
        startTime: "20:00",
        endTime: "21:00",
        timeSlotStart: 10,
        timeSlotEnd: 10,
        duration: 1,
        startTimePST: "13:00",
        endTimePST: "14:00",
      },
      {
        id: 7,
        title: "LIVE TOUR 2",
        speaker: "Digital Fashion Week",
        type: "Tour",
        stage: "MainStage",
        startTime: "21:00",
        endTime: "22:00",
        timeSlotStart: 11,
        timeSlotEnd: 11,
        duration: 1,
        startTimePST: "14:00",
        endTimePST: "15:00",
      },
      {
        id: 8,
        title:
          "Your First Virtual Gallery: A Step-by-Step Build in Decentraland",
        speaker: "Nico Earnshaw",
        type: "Workshop",
        stage: "MainStage",
        startTime: "22:00",
        endTime: "23:00",
        timeSlotStart: 12,
        timeSlotEnd: 12,
        duration: 1,
        startTimePST: "15:00",
        endTimePST: "16:00",
      },
      {
        id: 9,
        title:
          "Behind the Build: How 7 Artists Turned Ideas into Immersive Art",
        speaker: "Dana Mart",
        type: "Workshop",
        stage: "MainStage",
        startTime: "23:00",
        endTime: "00:00",
        timeSlotStart: 13,
        timeSlotEnd: 13,
        duration: 1,
        startTimePST: "16:00",
        endTimePST: "17:00",
      },
      {
        id: Math.random(),
        title:
          "Find Your Next Collab! Easy, Fun Networking Led by a Virtual Host",
        speaker: "Bay Backner",
        type: "Workshop",
        stage: "MainStage",
        startTime: "00:00",
        endTime: "01:00",
        timeSlotStart: 14,
        timeSlotEnd: 14,
        duration: 1,
        startTimePST: "17:00",
        endTimePST: "18:00",
      },
      {
        id: 10,
        title: "RAGE! Art & Industrial Music",
        speaker: "RAGE",
        type: "Party",
        stage: "MainStage",
        startTime: "01:00",
        endTime: "02:00",
        timeSlotStart: 15,
        timeSlotEnd: 15,
        duration: 1,
        startTimePST: "18:00",
        endTimePST: "19:00",
      },
    ],
  },
  "sept-25": {
    MainStage: [
      {
        id: 11,
        title: "The Insider’s Guide to Creating for Virtual Art Shows",
        speaker: "Bay Backner & Guests",
        type: "X Space",
        stage: "MainStage",
        startTime: "11:00",
        endTime: "12:00",
        timeSlotStart: 1,
        timeSlotEnd: 1,
        duration: 1,
        startTimePST: "04:00",
        endTimePST: "05:00",
      },
      {
        id: 12,
        title: "Brave for Creators: Privacy, Web3, and Fair Rewards",
        speaker: "Brave",
        type: "Workshop",
        stage: "MainStage",
        startTime: "12:00",
        endTime: "13:00",
        timeSlotStart: 2,
        timeSlotEnd: 2,
        duration: 1,
        startTimePST: "05:00",
        endTimePST: "06:00",
      },
      {
        id: 13,
        title: "LIVE TOUR 3",
        speaker: "Art Week Artists",
        type: "Tour",
        stage: "MainStage",
        startTime: "13:00",
        endTime: "14:00",
        timeSlotStart: 3,
        timeSlotEnd: 3,
        duration: 1,
        startTimePST: "06:00",
        endTimePST: "07:00",
      },
      {
        id: 14,
        title: "How to Open & Promote Your Own Gallery in Decentraland",
        speaker: "Nico Earnshaw & Dana Mart",
        type: "Workshop",
        stage: "MainStage",
        startTime: "14:00",
        endTime: "15:00",
        timeSlotStart: 4,
        timeSlotEnd: 4,
        duration: 1,
        startTimePST: "07:00",
        endTimePST: "08:00",
      },
      {
        id: 15,
        title: "Digital to Physical: Take Your 3D Art Anywhere with AR",
        speaker: "Artivive",
        type: "Workshop",
        stage: "MainStage",
        startTime: "15:00",
        endTime: "16:00",
        timeSlotStart: 5,
        timeSlotEnd: 5,
        duration: 1,
        startTimePST: "08:00",
        endTimePST: "09:00",
      },
      {
        id: 16,
        title:
          "Curator Secrets: How to Be Selected for Art Shows — Virtual and IRL",
        speaker: "Bay Backner",
        type: "Workshop",
        stage: "MainStage",
        startTime: "16:00",
        endTime: "17:00",
        timeSlotStart: 6,
        timeSlotEnd: 6,
        duration: 1,
        startTimePST: "09:00",
        endTimePST: "10:00",
      },
      {
        id: Math.random(),
        title: "The WIP TOUR at Decentraland Art Week",
        speaker: "The WIP Meetup",
        type: "Tour",
        stage: "MainStage",
        startTime: "19:00",
        endTime: "20:00",
        timeSlotStart: 9,
        timeSlotEnd: 9,
        duration: 1,
        startTimePST: "12:00",
        endTimePST: "13:00",
      },
      {
        id: 17,
        title: "Brave at Decentraland Art Week: Pro Tips for Creators",
        speaker: "Brave x Decentraland",
        type: "X Space",
        stage: "MainStage",
        startTime: "20:00",
        endTime: "21:00",
        timeSlotStart: 10,
        timeSlotEnd: 10,
        duration: 1,
        startTimePST: "13:00",
        endTimePST: "14:00",
      },
      {
        id: 18,
        title: "Using Brave as a Creator: Get Rewarded while Getting Noticed",
        speaker: "Brave",
        type: "Workshop",
        stage: "MainStage",
        startTime: "21:00",
        endTime: "22:00",
        timeSlotStart: 11,
        timeSlotEnd: 11,
        duration: 1,
        startTimePST: "14:00",
        endTimePST: "15:00",
      },
      {
        id: 19,
        title: "How to Open & Promote Your Own Gallery in Decentraland",
        speaker: "Nico Earnshaw & Dana Mart",
        type: "Workshop",
        stage: "MainStage",
        startTime: "22:00",
        endTime: "23:00",
        timeSlotStart: 12,
        timeSlotEnd: 12,
        duration: 1,
        startTimePST: "15:00",
        endTimePST: "16:00",
      },
      {
        id: 20,
        title: "Digital to Physical: Take Your 3D Art Anywhere with AR",
        speaker: "Artivive",
        type: "Workshop",
        stage: "MainStage",
        startTime: "23:00",
        endTime: "00:00",
        timeSlotStart: 13,
        timeSlotEnd: 13,
        duration: 1,
        startTimePST: "16:00",
        endTimePST: "17:00",
      },
      {
        id: Math.random(),
        title:
          "Curator Secrets: How to Be Selected for Art Shows — Virtual and IRL",
        speaker: "Bay Backner",
        type: "Workshop",
        stage: "MainStage",
        startTime: "00:00",
        endTime: "01:00",
        timeSlotStart: 14,
        timeSlotEnd: 14,
        duration: 1,
        startTimePST: "17:00",
        endTimePST: "18:00",
      },
      {
        id: 21,
        title: "Grass to the Moon - DJ Abillitea live in Facemoon Gallery",
        speaker: "Facemoon",
        type: "Party",
        stage: "MainStage",
        startTime: "01:00",
        endTime: "02:00",
        timeSlotStart: 15,
        timeSlotEnd: 15,
        duration: 1,
        startTimePST: "18:00",
        endTimePST: "19:00",
      },
      {
        id: 43,
        title: "Community Art Tour by CBD",
        speaker: "Community Building DCL",
        type: "Tour",
        stage: "MainStage",
        startTime: "02:00",
        endTime: "02:00",
        timeSlotStart: 16,
        timeSlotEnd: 16,
        duration: 1,
        startTimePST: "19:00",
        endTimePST: "19:00",
      },
    ],
  },
  "sept-26": {
    MainStage: [
      {
        id: 22,
        title: "AI for 3D Art: A Beginner’s Guide",
        speaker: "Bay Backner & Guests",
        type: "X Space",
        stage: "MainStage",
        startTime: "11:00",
        endTime: "12:00",
        timeSlotStart: 1,
        timeSlotEnd: 1,
        duration: 1,
        startTimePST: "04:00",
        endTimePST: "05:00",
      },
      {
        id: 23,
        title:
          "Master AI Design with ImagineArt’s Creative Playground & Creator Community",
        speaker: "Imagine Art",
        type: "Workshop",
        stage: "MainStage",
        startTime: "12:00",
        endTime: "13:00",
        timeSlotStart: 2,
        timeSlotEnd: 2,
        duration: 1,
        startTimePST: "05:00",
        endTimePST: "06:00",
      },
      {
        id: 24,
        title: "LIVE TOUR 6",
        speaker: "Art Week Artists",
        type: "Tour",
        stage: "MainStage",
        startTime: "13:00",
        endTime: "14:00",
        timeSlotStart: 3,
        timeSlotEnd: 3,
        duration: 1,
        startTimePST: "06:00",
        endTimePST: "07:00",
      },
      {
        id: 25,
        title: "AI to 3D in Minutes: How to Create Models Ready for Your World",
        speaker: "Sloyd",
        type: "Workshop",
        stage: "MainStage",
        startTime: "14:00",
        endTime: "15:00",
        timeSlotStart: 4,
        timeSlotEnd: 4,
        duration: 1,
        startTimePST: "07:00",
        endTimePST: "08:00",
      },
      {
        id: 26,
        title: "Instant Assets: Creating Decentraland-Ready 3D Models",
        speaker: "CSM",
        type: "Workshop",
        stage: "MainStage",
        startTime: "15:00",
        endTime: "16:00",
        timeSlotStart: 5,
        timeSlotEnd: 5,
        duration: 1,
        startTimePST: "08:00",
        endTimePST: "09:00",
      },
      {
        id: 27,
        title: "AI-Powered Creation in Decentraland",
        speaker: "Kim Currier & Guests",
        type: "X Space",
        stage: "MainStage",
        startTime: "20:00",
        endTime: "21:00",
        timeSlotStart: 10,
        timeSlotEnd: 10,
        duration: 1,
        startTimePST: "13:00",
        endTimePST: "14:00",
      },
      {
        id: 28,
        title: "LIVE TOUR 7",
        speaker: "Art Week Artists",
        type: "Tour",
        stage: "MainStage",
        startTime: "21:00",
        endTime: "22:00",
        timeSlotStart: 11,
        timeSlotEnd: 11,
        duration: 1,
        startTimePST: "14:00",
        endTimePST: "15:00",
      },
      {
        id: 29,
        title:
          "Master AI Design with ImagineArt's Creative Playground & Creator Community",
        speaker: "Imagine Art",
        type: "Workshop",
        stage: "MainStage",
        startTime: "22:00",
        endTime: "23:00",
        timeSlotStart: 12,
        timeSlotEnd: 12,
        duration: 1,
        startTimePST: "15:00",
        endTimePST: "16:00",
      },
      {
        id: 30,
        title: "AI to 3D in Minutes: How to Create Models Ready for Your World",
        speaker: "Sloyd",
        type: "Workshop",
        stage: "MainStage",
        startTime: "23:00",
        endTime: "00:00",
        timeSlotStart: 13,
        timeSlotEnd: 13,
        duration: 1,
        startTimePST: "16:00",
        endTimePST: "17:00",
      },
      {
        id: Math.random(),
        title: "Instant Assets: Creating Decentraland-Ready 3D Models",
        speaker: "CSM",
        type: "Workshop",
        stage: "MainStage",
        startTime: "23:00",
        endTime: "00:00",
        timeSlotStart: 14,
        timeSlotEnd: 14,
        duration: 1,
        startTimePST: "16:00",
        endTimePST: "17:00",
      },
      {
        id: 31,
        title: "Meta Beast Roaming Party @ Roustan Gallery",
        speaker: "Roustan/DJ Make",
        type: "Party",
        stage: "MainStage",
        startTime: "01:00",
        endTime: "02:00",
        timeSlotStart: 15,
        timeSlotEnd: 15,
        duration: 1,
        startTimePST: "18:00",
        endTimePST: "19:00",
      },
    ],
  },
  "sept-27": {
    MainStage: [
      {
        id: 32,
        title:
          "Behind the Building: How 7 Artists Turned Ideas into Immersive Art",
        speaker: "Dana Mart",
        type: "Workshop",
        stage: "MainStage",
        startTime: "12:00",
        endTime: "13:00",
        timeSlotStart: 2,
        timeSlotEnd: 2,
        duration: 1,
        startTimePST: "05:00",
        endTimePST: "06:00",
      },
      {
        id: 33,
        title:
          "Your First Virtual Gallery: A Step-by-Step Build in Decentraland",
        speaker: "Nico Earnshaw",
        type: "Workshop",
        stage: "MainStage",
        startTime: "13:00",
        endTime: "14:00",
        timeSlotStart: 3,
        timeSlotEnd: 3,
        duration: 1,
        startTimePST: "06:00",
        endTimePST: "07:00",
      },
      {
        id: 34,
        title: "How to Open & Promote Your Own Gallery in Decentraland",
        speaker: "Nico Earnshaw & Dana Mart",
        type: "Workshop",
        stage: "MainStage",
        startTime: "14:00",
        endTime: "15:00",
        timeSlotStart: 4,
        timeSlotEnd: 4,
        duration: 1,
        startTimePST: "07:00",
        endTimePST: "08:00",
      },
      {
        id: 35,
        title:
          "Curator Secrets: How to Be Selected for Art Shows — Virtual and IRL",
        speaker: "Bay Backner",
        type: "Workshop",
        stage: "MainStage",
        startTime: "15:00",
        endTime: "16:00",
        timeSlotStart: 5,
        timeSlotEnd: 5,
        duration: 1,
        startTimePST: "08:00",
        endTimePST: "09:00",
      },
      {
        id: 36,
        title: "Using Brave as a Creator: Get Rewarded while Getting Noticed",
        speaker: "Brave",
        type: "Workshop",
        stage: "MainStage",
        startTime: "16:00",
        endTime: "17:00",
        timeSlotStart: 6,
        timeSlotEnd: 6,
        duration: 1,
        startTimePST: "09:00",
        endTimePST: "10:00",
      },
      {
        id: 37,
        title:
          "Master AI Design with ImagineArt’s Creative Playground & Creator Community",
        speaker: "Imagine Art",
        type: "Workshop",
        stage: "MainStage",
        startTime: "17:00",
        endTime: "18:00",
        timeSlotStart: 7,
        timeSlotEnd: 7,
        duration: 1,
        startTimePST: "10:00",
        endTimePST: "11:00",
      },
      {
        id: 38,
        title: "AI to 3D in Minutes: How to Create Models Ready for Your World",
        speaker: "Sloyd",
        type: "Workshop",
        stage: "MainStage",
        startTime: "18:00",
        endTime: "19:00",
        timeSlotStart: 8,
        timeSlotEnd: 8,
        duration: 1,
        startTimePST: "11:00",
        endTimePST: "12:00",
      },
      {
        id: Math.random(),
        title:
          "Digital to Physical: Take Your Decentraland Art Anywhere with AR",
        speaker: "Artivive",
        type: "Workshop",
        stage: "MainStage",
        startTime: "19:00",
        endTime: "20:00",
        timeSlotStart: 9,
        timeSlotEnd: 9,
        duration: 1,
        startTimePST: "12:00",
        endTimePST: "13:00",
      },
      {
        id: 39,
        title: "Instant Assets: Creating Decentraland-Ready 3D Models",
        speaker: "CSM",
        type: "Workshop",
        stage: "MainStage",
        startTime: "20:00",
        endTime: "21:00",
        timeSlotStart: 10,
        timeSlotEnd: 10,
        duration: 1,
        startTimePST: "13:00",
        endTimePST: "14:00",
      },
      {
        id: 40,
        title:
          "Your First Virtual Gallery: A Step-by-Step Build in Decentraland",
        speaker: "Nico Earnshaw",
        type: "Workshop",
        stage: "MainStage",
        startTime: "21:00",
        endTime: "22:00",
        timeSlotStart: 11,
        timeSlotEnd: 11,
        duration: 1,
        startTimePST: "14:00",
        endTimePST: "15:00",
      },
      {
        id: 41,
        title: "How to Open & Promote Your Own Gallery in Decentraland",
        speaker: "Nico Earnshaw & Dana Mart",
        type: "Workshop",
        stage: "MainStage",
        startTime: "22:00",
        endTime: "23:00",
        timeSlotStart: 12,
        timeSlotEnd: 12,
        duration: 1,
        startTimePST: "15:00",
        endTimePST: "16:00",
      },
      {
        id: 42,
        title: "Audio Hot Lab Party w/ Silvio De Candia",
        speaker: "AudioHotLab",
        type: "Party",
        stage: "MainStage",
        startTime: "23:00",
        endTime: "00:00",
        timeSlotStart: 13,
        timeSlotEnd: 13,
        duration: 1,
        startTimePST: "16:00",
        endTimePST: "17:00",
      },
    ],
  },
}

const dateOptions = [
  { key: "sept-24", date: "SEPT 24", label: "Day One" },
  { key: "sept-25", date: "SEPT 25", label: "Day Two" },
  { key: "sept-26", date: "SEPT 26", label: "Day Three" },
  { key: "sept-27", date: "SEPT 27", label: "Day Four" },
] as const

export type { ScheduleEvent, StageSchedule, DaySchedule }

export { timeSlots, stages, scheduleData, dateOptions, convertToPST }
