export const artists = [
  {
    id: 1,
    name: 'Sara Shakeel',
    description: 'Descripción pendiente.',
    image: 'https://via.placeholder.com/800',
    link: 'https://www.google.com',
    studio: 'Studio 1',
    coordinates: { lat: 0, lng: 0 },
  },
  {
    id: 2,
    name: 'Johanna Jaskowska',
    description: 'Descripción pendiente.',
    image: 'https://via.placeholder.com/800',
    link: 'https://www.google.com',
    studio: 'Studio 2',
    coordinates: { lat: 0, lng: 0 },
  },
  {
    id: 3,
    name: 'Johanna Jaskowska',
    description: 'Descripción pendiente.',
    image: 'https://via.placeholder.com/800',
    link: 'https://www.google.com',
    studio: 'Studio 3',
    coordinates: { lat: 0, lng: 0 },
  },
  {
    id: 4,
    name: 'Micah Alhadeff',
    description: 'Descripción pendiente.',
    image: 'https://via.placeholder.com/800',
    link: 'https://www.google.com',
    studio: 'Studio 4',
    coordinates: { lat: 0, lng: 0 },
  },
  {
    id: 5,
    name: 'Carla Knopp',
    description: 'Descripción pendiente.',
    image: 'https://via.placeholder.com/800',
    link: 'https://www.google.com',
    studio: 'Studio 5',
    coordinates: { lat: 0, lng: 0 },
  },
  {
    id: 6,
    name: 'Sabato Visconti',
    description: 'Descripción pendiente.',
    image: 'https://via.placeholder.com/800',
    link: 'https://www.google.com',
    studio: 'Studio 6',
    coordinates: { lat: 0, lng: 0 },
  },
  {
    id: 7,
    name: 'Luis Llácer (LLACERART)',
    description: 'Descripción pendiente.',
    image: 'https://via.placeholder.com/800',
    link: 'https://www.google.com',
    studio: 'Studio 7',
    coordinates: { lat: 0, lng: 0 },
  },
  {
    id: 8,
    name: 'Carla Knopp',
    description: 'Descripción pendiente.',
    image: 'https://via.placeholder.com/800',
    link: 'https://www.google.com',
    studio: 'Studio 8',
    coordinates: { lat: 0, lng: 0 },
  },
  {
    id: 9,
    name: 'Carla Knopp',
    description: 'Descripción pendiente.',
    image: 'https://via.placeholder.com/800',
    link: 'https://www.google.com',
    studio: 'Studio 9',
    coordinates: { lat: 0, lng: 0 },
  },
  {
    id: 10,
    name: 'Luis Llácer (LLACERART)',
    description: 'Descripción pendiente.',
    image: 'https://via.placeholder.com/800',
    link: 'https://www.google.com',
    studio: 'Studio 10',
    coordinates: { lat: 0, lng: 0 },
  },
  {
    id: 11,
    name: 'Johanna Jaskowska',
    description: 'Descripción pendiente.',
    image: 'https://via.placeholder.com/800',
    link: 'https://www.google.com',
    studio: 'Studio 11',
    coordinates: { lat: 0, lng: 0 },
  },
  {
    id: 12,
    name: 'Amber Vittoria',
    description: 'Descripción pendiente.',
    image: 'https://via.placeholder.com/800',
    link: 'https://www.google.com',
    studio: 'Studio 12',
    coordinates: { lat: 0, lng: 0 },
  },
  {
    id: 13,
    name: 'Amber Vittoria',
    description: 'Descripción pendiente.',
    image: 'https://via.placeholder.com/800',
    link: 'https://www.google.com',
    studio: 'Studio 13',
    coordinates: { lat: 0, lng: 0 },
  },
  {
    id: 14,
    name: 'Sara Shakeel',
    description: 'Descripción pendiente.',
    image: 'https://via.placeholder.com/800',
    link: 'https://www.google.com',
    studio: 'Studio 14',
    coordinates: { lat: 0, lng: 0 },
  },
  {
    id: 15,
    name: 'Sara Shakeel',
    description: 'Descripción pendiente.',
    image: 'https://via.placeholder.com/800',
    link: 'https://www.google.com',
    studio: 'Studio 15',
    coordinates: { lat: 0, lng: 0 },
  },
  {
    id: 16,
    name: 'Carla Knopp',
    description: 'Descripción pendiente.',
    image: 'https://via.placeholder.com/800',
    link: 'https://www.google.com',
    studio: 'Studio 16',
    coordinates: { lat: 0, lng: 0 },
  },
  {
    id: 17,
    name: 'Luis Llácer (LLACERART)',
    description: 'Descripción pendiente.',
    image: 'https://via.placeholder.com/800',
    link: 'https://www.google.com',
    studio: 'Studio 17',
    coordinates: { lat: 0, lng: 0 },
  },
  {
    id: 18,
    name: 'Sara Shakeel',
    description: 'Descripción pendiente.',
    image: 'https://via.placeholder.com/800',
    link: 'https://www.google.com',
    studio: 'Studio 18',
    coordinates: { lat: 0, lng: 0 },
  },
  {
    id: 19,
    name: 'Micah Alhadeff',
    description: 'Descripción pendiente.',
    image: 'https://via.placeholder.com/800',
    link: 'https://www.google.com',
    studio: 'Studio 19',
    coordinates: { lat: 0, lng: 0 },
  },
  {
    id: 20,
    name: 'Luis Llácer (LLACERART)',
    description: 'Descripción pendiente.',
    image: 'https://via.placeholder.com/800',
    link: 'https://www.google.com',
    studio: 'Studio 20',
    coordinates: { lat: 0, lng: 0 },
  },
  {
    id: 21,
    name: 'Micah Alhadeff',
    description: 'Descripción pendiente.',
    image: 'https://via.placeholder.com/800',
    link: 'https://www.google.com',
    studio: 'Studio 21',
    coordinates: { lat: 0, lng: 0 },
  },
  {
    id: 22,
    name: 'Micah Alhadeff',
    description: 'Descripción pendiente.',
    image: 'https://via.placeholder.com/800',
    link: 'https://www.google.com',
    studio: 'Studio 22',
    coordinates: { lat: 0, lng: 0 },
  },
  {
    id: 23,
    name: 'Amber Vittoria',
    description: 'Descripción pendiente.',
    image: 'https://via.placeholder.com/800',
    link: 'https://www.google.com',
    studio: 'Studio 23',
    coordinates: { lat: 0, lng: 0 },
  },
  {
    id: 24,
    name: 'Luis Llácer (LLACERART)',
    description: 'Descripción pendiente.',
    image: 'https://via.placeholder.com/800',
    link: 'https://www.google.com',
    studio: 'Studio 24',
    coordinates: { lat: 0, lng: 0 },
  },
];
