const artists = [
  {
    id: 1,
    name: "Sara Shakeel",
    description: undefined,
    image: undefined,
    link: "https://github.com/decentraland-scenes/dcl_art_week_2025_a1",
    studio: "Low Poly Models",
    coordinates: {
      lat: -150.0,
      lng: -93.0,
    },
  },
  {
    id: 2,
    name: "Johanna Jaskowska",
    description: undefined,
    image: undefined,
    link: "https://github.com/decentraland-scenes/dcl_art_week_2025_a2",
    studio: "Nikki Fuego",
    coordinates: {
      lat: -150.0,
      lng: -96.0,
    },
  },
  {
    id: 3,
    name: "Amber Vittoria",
    description: undefined,
    image: undefined,
    link: "https://github.com/decentraland-scenes/dcl_art_week_2025_a3",
    studio: "DappCraft",
    coordinates: {
      lat: -149.0,
      lng: -82.0,
    },
  },
  {
    id: 4,
    name: "Clara Bacou",
    description: undefined,
    image: undefined,
    link: "https://github.com/decentraland-scenes/dcl_art_week_2025_a4",
    studio: "Cansy",
    coordinates: {
      lat: -148.0,
      lng: -84.0,
    },
  },
  {
    id: 5,
    name: "Micah Alhadeff",
    description: undefined,
    image: undefined,
    link: "https://github.com/decentraland-scenes/dcl_art_week_2025_a5",
    studio: "Micah Alhadeff",
    coordinates: {
      lat: -149.0,
      lng: -86.0,
    },
  },
  {
    id: 6,
    name: "Sabato Visconti",
    description: undefined,
    image: undefined,
    link: "https://github.com/decentraland-scenes/dcl_art_week_2025_a6",
    studio: "Sabato Visconti",
    coordinates: {
      lat: -135.0,
      lng: -95.0,
    },
  },
  {
    id: 7,
    name: "Luis Llácer (LLACERART)",
    description: undefined,
    image: undefined,
    link: "https://github.com/decentraland-scenes/dcl_art_week_2025_a7",
    studio: "OhMyVerse",
    coordinates: {
      lat: -133.0,
      lng: -95.0,
    },
  },
  {
    id: 8,
    name: "Carla Knopp",
    description: undefined,
    image: undefined,
    link: "https://github.com/decentraland-scenes/dcl_art_week_2025_a8",
    studio: "Carla Knopp",
    coordinates: {
      lat: -141.0,
      lng: -93.0,
    },
  },
  {
    id: 9,
    name: "Emma Shapiro & Savannah Spirit",
    description: undefined,
    image: undefined,
    link: "https://github.com/decentraland-scenes/dcl_art_week_2025_a9",
    studio: "Imagine to Create",
    coordinates: {
      lat: -142.0,
      lng: -81.0,
    },
  },
  {
    id: 10,
    name: "Antonio Azzolino",
    description: undefined,
    image: undefined,
    link: "https://github.com/decentraland-scenes/dcl_art_week_2025_a10",
    studio: "Antonio Azzolino",
    coordinates: {
      lat: -142.0,
      lng: -83.0,
    },
  },
  {
    id: 11,
    name: "OgiWorlds",
    description: undefined,
    image: undefined,
    link: "https://github.com/decentraland-scenes/dcl_art_week_2025_a11",
    studio: "OgiWorlds",
    coordinates: {
      lat: -139.0,
      lng: -81.0,
    },
  },
  {
    id: 12,
    name: "Mafin & Lazaro",
    description: undefined,
    image: undefined,
    link: "https://github.com/decentraland-scenes/dcl_art_week_2025_a12",
    studio: "Impossible Studios",
    coordinates: {
      lat: -139.0,
      lng: -83.0,
    },
  },
  {
    id: 13,
    name: "Elisaveta Sivas",
    description: undefined,
    image: undefined,
    link: "https://github.com/decentraland-scenes/dcl_art_week_2025_a13",
    studio: "Vegas City",
    coordinates: {
      lat: -142.0,
      lng: -86.0,
    },
  },
  {
    id: 14,
    name: "Clara Ohde",
    description: undefined,
    image: undefined,
    link: "https://github.com/decentraland-scenes/dcl_art_week_2025_a14",
    studio: "Metarizk",
    coordinates: {
      lat: -142.0,
      lng: -89.0,
    },
  },
  {
    id: 15,
    name: "Iacob Visual",
    description: undefined,
    image: undefined,
    link: "https://github.com/decentraland-scenes/dcl_art_week_2025_a15",
    studio: "Metadoge",
    coordinates: {
      lat: -139.0,
      lng: -89.0,
    },
  },
  {
    id: 16,
    name: "PepeGawd",
    description: undefined,
    image: undefined,
    link: "https://github.com/decentraland-scenes/dcl_art_week_2025_a16",
    studio: "PepeGawd",
    coordinates: {
      lat: -147.0,
      lng: -95.0,
    },
  },
  {
    id: 17,
    name: "Bosque Gracias",
    description: undefined,
    image: undefined,
    link: "https://github.com/decentraland-scenes/dcl_art_week_2025_a17",
    studio: "Coding Cave",
    coordinates: {
      lat: -136.0,
      lng: -83.0,
    },
  },
  {
    id: 18,
    name: "Paradigmstories ",
    description: undefined,
    image: undefined,
    link: "https://github.com/decentraland-scenes/dcl_art_week_2025_a18",
    studio: "Jeunissemble Studio",
    coordinates: {
      lat: -133.0,
      lng: -83.0,
    },
  },
  {
    id: 19,
    name: "Agustin Di Luciano & Melina Ojagnan ",
    description: undefined,
    image: undefined,
    link: "https://github.com/decentraland-scenes/dcl_art_week_2025_a19",
    studio: "Monsterhall",
    coordinates: {
      lat: -135.0,
      lng: -80.0,
    },
  },
  {
    id: 20,
    name: "Hayabusa",
    description: undefined,
    image: undefined,
    link: "https://github.com/decentraland-scenes/dcl_art_week_2025_a20",
    studio: "Hayabusa",
    coordinates: {
      lat: -136.0,
      lng: -86.0,
    },
  },
  {
    id: 21,
    name: "REZON",
    description: undefined,
    image: undefined,
    link: "https://github.com/decentraland-scenes/dcl_art_week_2025_a21",
    studio: "REZON",
    coordinates: {
      lat: -136.0,
      lng: -89.0,
    },
  },
  {
    id: 22,
    name: "Cybermike",
    description: undefined,
    image: undefined,
    link: "https://github.com/decentraland-scenes/dcl_art_week_2025_a22",
    studio: "Cybermike",
    coordinates: {
      lat: -133.0,
      lng: -88.0,
    },
  },
  {
    id: 23,
    name: "Carlos Muñoz",
    description: undefined,
    image: undefined,
    link: "https://github.com/decentraland-scenes/dcl_art_week_2025_a23",
    studio: "ZCayel",
    coordinates: {
      lat: -135.0,
      lng: -91.0,
    },
  },
  {
    id: 24,
    name: "Chrono T",
    description: undefined,
    image: undefined,
    link: "https://github.com/decentraland-scenes/dcl_art_week_2025_a24",
    studio: "Chrono T",
    coordinates: {
      lat: -133.0,
      lng: -91.0,
    },
  },
  {
    id: 25,
    name: "Digital Fashion Week Showroom",
    description: undefined,
    image: undefined,
    link: "https://github.com/decentraland-scenes/dcl_art_week_2025_boutique",
    studio: "Low Poly Models",
    coordinates: {
      lat: -147.0,
      lng: -95.0,
    },
  },
  {
    id: 26,
    name: "The Photography Gallery",
    description: undefined,
    image: undefined,
    link: "https://github.com/decentraland-scenes/dcl_art_week_2025_gallery",
    studio: "Carlos Mu",
    coordinates: {
      lat: -133.0,
      lng: -86.0,
    },
  },
  {
    id: 27,
    name: "Art Visitor Centre",
    description: undefined,
    image: undefined,
    link: "https://github.com/decentraland-scenes/dcl_art_week_2025_visitor_center",
    studio: "OVA",
    coordinates: {
      lat: -140.0,
      lng: -86.0,
    },
  },
]

export { artists }
