const artistsAndCurators = [
  'Sara Shakeel',
  'Johanna Jaskowska',
  'Amber Vittoria',
  'Clara Bacou',
  'Micah Alhadeff',
  'Sabato Visconti',
  'Luis Llácer',
  'Carla Knopp',
  'Emma Shapiro & Savannah',
  'Spirit Antonio Azzolino',
  'OgiWorlds',
  'Mafin & Lazaro',
  'Elisaveta Sivas',
  'Clara Ohde',
  'Iacob Visual',
  'PepeGawd',
  'Bosque Gracias Paradigmstories',
  'Agustin Di Luciano & Melina',
  'Ojogann Hayabusa',
  'REZON',
  'Cybermike',
  'Carlos Muñoz',
  'Chrono T',
];

const studios = [
  'OVA.DESIGN',
  'Low Poly Models',
  'Nikki Fuego',
  'DAPPCRAFT',
  'Cansy',
  'Carlos Mu',
  'OhMyVerse',
  'Imagine to Create',
  'Impossible Studios',
  'Vegas City',
  'Metarizk',
  'Metadoge',
  'The Coding Cave',
  'Jeuniessemble Studio',
  'Monsterhall',
  'ZCayel',
];

export { artistsAndCurators, studios };
